### ISSUE TITLE
Not working with PHP 8.1

### ISSUE THREAD

**Issue by dzdaniel** [getbread/magento-v2-bread#171]
Hi Bread team,

I got some errors when upgrade my PHP to 8.1. Most of them are passing null to parameter of strtotime(), preg_replace(), explode(). Could you verify all the code and make sure it's compatible with PHP 8.1?

**Comment by Januszpl** [comment]
@dzdaniel I haven't check it yet but it seems they fixed it here: https://github.com/getbread/magento-v2-bread/releases/tag/v2.1.4
